### ISSUE TITLE
Style elements aren't implementing style type context correctly

### ISSUE THREAD

**Issue by Glutnix** [henjue/vue-for-idea#1]
If I have 

``` html

<style lang="scss">
  .Alert {
    $color: #ddd;
    position: relative;
    background: $color;
    border: 1px solid darken($color, 10%);
    padding: 1em;
  }
</style>
```

I'm not getting the same SCSS treatment that I would be getting in an actual SCSS file. SCSS syntax highlighting isn't being applied, autocompletes aren't autocompleting.

At very least, the errors I'm getting within the style attribute don't seem to be SCSS errors but CSS errors:
- property name expected
- a term expected
- a term expected

PhpStorm 10.0.2, vue-for-idea 1.0.1.

**Comment by springeye** [comment]
@Glutnix Thank you. The first time I intend to develop a complete full idea plug-ins, because I like vue. So is learning, the problem may need some time before I deal with!

**Comment by springeye** [comment]
Already exist Similar problems [issues 3](https://github.com/henjue/vue-for-idea/issues/3)
