### ISSUE TITLE
Goes badly wrong with the latest WebStorm EAP

### ISSUE THREAD

**Issue by iby** [henjue/vue-for-idea#18]
![image](https://cloud.githubusercontent.com/assets/1086845/13549665/78f846ee-e31b-11e5-8ffd-4ef586bde98c.png)

**Comment by TinoGroteloh** [comment]
+1

**Comment by springeye** [comment]
Details are? Is it the same as the #22  ？？

**Comment by iby** [comment]
Looks like.

**Comment by springeye** [comment]
please update to 1.0.5
