### ISSUE TITLE
es6 ()=>{} not supported?

### ISSUE THREAD

**Issue by tommyZZM** [henjue/vue-for-idea#20]

**Comment by awdyer** [comment]
Add `type="text/babel"` to the script tag, as per #3.

**Comment by springeye** [comment]
see #3

**Comment by alsotang** [comment]
I already add `type="text/babel"`, but it seems not work

![image](https://cloud.githubusercontent.com/assets/1147375/16517390/afcdb15e-3faf-11e6-9558-4af1bf1631fc.png)

**Comment by fish-ball** [comment]
http://stackoverflow.com/a/38141782/2544762 Try `lang="babel"` instead.

**Comment by alsotang** [comment]
`lang="babel"` works!

**Comment by kvzn** [comment]
Why was this issue closed? It hasn't been fixed, even ```lang="babel"``` is a bad idea, which depends on  babel-loader
