### ISSUE TITLE
<style lang="scss"> not supported?

### ISSUE THREAD

**Issue by cnxxg** [henjue/vue-for-idea#21]
![image](https://cloud.githubusercontent.com/assets/3077057/13693453/464da3aa-e786-11e5-8470-e317e54ae674.png)

**Comment by springeye** [comment]
@cnxxg The temporary refuse scheme, add type= "scss"

**Comment by cnxxg** [comment]
@henjue seems to be of no effect!
![image](https://cloud.githubusercontent.com/assets/3077057/13700915/e605999c-e7be-11e5-945b-080a3e5bcb83.png)

**Comment by luwenjin** [comment]
use this
`<style lang="scss" rel="stylesheet/scss">`

**Comment by zhangchao828** [comment]
@luwenjin 像你那样设置了style lang="scss" rel="stylesheet/scss"之后还是不行，和webstorm版本有关吗，我的是11.0.1

**Comment by callmewhy** [comment]
@luwenjin 👍 

It works, my version is: 

```
WebStorm 2016.1.3
Build #WS-145.1616, built on May 27, 2016
```

**Comment by springeye** [comment]
Please update version to 1.0.7
1.0.7 support LESS,SASS,SCSS,Stylus,CSS,ES6,CoffeeScript,JavaScript
