### ISSUE TITLE
Project leak in attributes provider

### ISSUE THREAD

**Issue by denofevil** [henjue/vue-for-idea#28]
Storing project component inside of the extension point is causing project leak:
https://github.com/henjue/vue-for-idea/blob/master/src/main/java/io/j99/idea/vue/component/VueAttributeDescriptorProvider.java#L12.
<img width="894" alt="screen shot 2016-04-28 at 11 19 11" src="https://cloud.githubusercontent.com/assets/32124/14879646/7a001ed2-0d3b-11e6-962c-b04c44cef042.png">

I think this field is not needed, it can be replaced with local variable declaration.

**Comment by springeye** [comment]
The future will be rewritten. This plugin is currently used for learning

**Comment by denofevil** [comment]
I find it weird to close the issue that is still present. It's just a matter of deleting 4 lines of code, do you need PR for that?

**Comment by springeye** [comment]
I don't care about it at the present, for me it is more about learning how to develop plug-ins, and the second is to do it well.
