### ISSUE TITLE
ES6 support in <script> block

### ISSUE THREAD

**Issue by probil** [henjue/vue-for-idea#3]
I have configured ES6 as default JavaScript version, but when I use ES6 syntax inside `<script>` block WebStorm lint me "error syntax". 
![Error in arrow function](http://i.imgur.com/Z8FGyLr.png)

Do you have the same issue? Maybe, this could be fixed by this plugin? 
There is no such issue when I use `arrow function` inside *.js files

**Comment by agileago** [comment]
@probil you can add  `type="text/babel"` to solve it
![image](https://cloud.githubusercontent.com/assets/11799110/12215730/e5d1ba78-b703-11e5-842b-738ffb280af1.png)

**Comment by probil** [comment]
@agileago Thanks for the advice! Work as expected now.

So, maybe `vue-for-idea` should add it automatically on `File > New > Vue Component`?

**Comment by springeye** [comment]
@probil new version is supported
![qq 20160112173433](https://cloud.githubusercontent.com/assets/1314740/12259787/e5022708-b952-11e5-9233-faeb0ff6fcaf.png)

**Comment by probil** [comment]
After plugin update I have created new `Vue File`.

![Emm](http://i.imgur.com/uWXO0HM.png)

And I don't see `type="text/babel` in script tag. So, ES6 syntax still not working. There is also error in code.

**Comment by springeye** [comment]
@probil ES6 the problem may be in the next period of time to be able to deal with. Because at the moment I am not very well aware of the idea plug-in development and syntax analysis. In the learning...

**Comment by richarddewit** [comment]
@probil - Default it's ES5, if you want to use ES6 you'd have to put `type="text/babel` there yourself.

@henjue - would be nice if people could choose which `type` of script/css/template they want by default in the settings

Example (_dropdowns_):
**Preferences -> Languages & Frameworks -> Vue**

```
                           ________________
                           |          |   |
Default stylesheet type:   | CSS      | v |
                           |__________|___|
                           |          |
                           | - SASS   |
                           | - Stylus |
                           | - Less   |
                           |__________|

                           ________________________
                           |                  |   |
Default script type:       | JavaScript (ES5) | v |
                           |__________________|___|
                           |                  |
                           | - CoffeeScript   |
                           | - ES6/Babel      |
                           | - TypeScript     |
                           |__________________|

                           ____________________
                           |              |   |
Default template type:     | HTML         | v |
                           |______________|___|
                           |              |
                           | - Jade       |
                           | - Handlebars |
                           |______________|
```

**Comment by springeye** [comment]
@richarddewit I want to according to Lang, and then deal with the code in tag

**Comment by JoshZA** [comment]
:+1: for dropdowns

**Comment by exotfboy** [comment]
Hi,, event I add the `type = text/babel`, idea can not recognize the arrow function in the `.vue` file:

![1](https://cloud.githubusercontent.com/assets/16457917/13372292/f294c228-dd78-11e5-8452-5c35bcc15e9f.png)

However, in a pure .js script, the arrow function can be recognized:
![2](https://cloud.githubusercontent.com/assets/16457917/13372293/f2b74fbe-dd78-11e5-9f90-9b4737042f1f.png)

What's going on ?

**Comment by probil** [comment]
@exotfboy 
What JetBrains IDE do you use? WebStorm/PhpStorm/IntelliJ IDEA?
Could you upload example somewhere?

**Comment by agileago** [comment]
@probil   now webstorm eap 12 support inline sass/less . like this
![image](https://cloud.githubusercontent.com/assets/11799110/13378982/878170f4-de53-11e5-9926-4bd6fdba4b4c.png)

it is great!

**Comment by luwenjin** [comment]
@henjue According to lang will be best.
es6/coffeescript/less/scss all have workarounds.
but `<template lang="jade">` has no way to trigger syntax highlight.

**Comment by springeye** [comment]
Please update version to 1.0.7
1.0.7 support LESS,SASS,SCSS,Stylus,CSS,ES6,CoffeeScript,JavaScript

**Comment by szkrd** [comment]
No, it doesn't work here either.
Webstorm 11.0.4
![screen shot 2016-06-30 at 21 52 48](https://cloud.githubusercontent.com/assets/1073260/16502106/ff172f22-3f0c-11e6-8ac9-17995b6a04e5.png)
![screen shot 2016-06-30 at 21 51 43](https://cloud.githubusercontent.com/assets/1073260/16502107/ff3544f8-3f0c-11e6-8c43-ecefddbbb118.png)

**Comment by probil** [comment]
Yeah. Plugin works strange. So, I have deleted it and use `type="text/babel"` instead. 
:disappointed: 
Plugin rather confuses than helps.

**Comment by springeye** [comment]
Do not use the type attribute, use the lang,about vue-loader see http://vue-loader.vuejs.org/en/index.html

**Comment by szkrd** [comment]
Maybe I'm still missing something. Could you attach a screenshot with your settings and fat arrows not underlined? It would be really helpful! Vue-loader is 8.3.0, thank you!

![screen shot 2016-07-04 at 20 56 43](https://cloud.githubusercontent.com/assets/1073260/16568397/0bf83d74-422a-11e6-9e3a-acbda90e12d3.png)
![screen shot 2016-07-04 at 20 54 19](https://cloud.githubusercontent.com/assets/1073260/16568399/0c0e17de-422a-11e6-878d-84ae5777caa7.png)
![screen shot 2016-07-04 at 20 53 59](https://cloud.githubusercontent.com/assets/1073260/16568400/0c1838ae-422a-11e6-8bc4-c860ed2022e6.png)

**Comment by springeye** [comment]
@szkrd use lang="javascript",not use "text/javascript",see http://vue-loader.vuejs.org/en/index.html

**Comment by szkrd** [comment]
Unfortunately that didn't help :(

![16-07-07](https://cloud.githubusercontent.com/assets/1073260/16645573/39bfc586-4425-11e6-8f74-263e64c0c66c.PNG)

**Comment by rockxsj** [comment]
@szkrd I have the same problem :(

**Comment by wafs** [comment]
@szkrd @rockxsj @henjue 
The way to get es6 working is **not** lang="javascript", but in fact lang="babel" (not sure why this works over your official word of mouth though!)

![image](https://cloud.githubusercontent.com/assets/5717802/16700849/7b99f3f2-459f-11e6-8d9a-d7769c7215e1.png)

![image](https://cloud.githubusercontent.com/assets/5717802/16700864/915855a8-459f-11e6-81b5-d5f5a9bd4c6c.png)

http://stackoverflow.com/a/38141782

**Comment by szkrd** [comment]
@wafs you are my hero

**Comment by rockxsj** [comment]
@wafs thanks!    upgrade webstorm to 2016.2,the bug has fixed. 👍

**Comment by kevinzheng** [comment]
Why was this issue closed? It hasn't been fixed, even lang="babel" is a bad idea, which depends on babel-loader
