### ISSUE TITLE
lang="jade" not supported

### ISSUE THREAD

**Issue by ianberdin** [henjue/vue-for-idea#35]

**Comment by daimon99** [comment]
什么时候能够支持<template lang="jade">啊。
实在太喜欢jade了。现在就atom对vue中的jade支持还凑活。
真希望@henjue能够尽快支持jade!

**Comment by springeye** [comment]
@daimon99 jade在webstorm里才有，预计下下周有空会准备加入template部分的处理。最近个人时间有限，公司太忙了。几乎每天加班到半夜。只能用业余时间来搞

**Comment by daimon99** [comment]
这个插件实在不错。要是有个简单的编译说明，我也可以试试一起来完善下啊。

**Comment by springeye** [comment]
@daimon99 

``` bash
git clone https://github.com/henjue/vue-for-idea -b develop
cd vue-for-idea
./gradlew runIdea
```

**Comment by zhuzhuaicoding** [comment]
快支持

**Comment by daimon99** [comment]
出一个错，提示没有password属性。然后把`build.gradle`里面的`password Boolean.valueOf(System.getenv('CI')) ? System.getenv('PLUGIN_PASSWORD') : PLUGIN_PASSWORD`注释掉，能执行了。但是运行的时候打开了IDEA，然后，然后，就不知道怎么办了。。

**Comment by daimon99** [comment]
大概扫了一遍代码。原来只处理了script和style标签中的lang。template标签根本就没处理lang。这个好处理吗？要是体力活，好描述，我可以试着改改。

**Comment by daimon99** [comment]
没做过idea插件开发，另外很多年没摸java了，变化真大啊。gradle也完全没碰过。

**Comment by psi-4ward** [comment]
can anyone explain the state of jade/pug injection in english? i see only square chars ;)

**Comment by daimon99** [comment]
They say the author maybe will let it support jade/pug in the future, but now do not...

**Comment by psi-4ward** [comment]
This is a feature from vue-for-idea? I tried to inject pug-lang but I can not chose it from the list of available languages.

**Comment by springeye** [comment]
@daimon99 我忘记是develop分之还是pw分之我开始加入了对template处理的一部分代码了，后来一直忙。最近也天天在外面怕创业的事情，时间很少。。。

**Comment by abou7mied** [comment]
Any updates to this issue ?
It's really annoying problem that I can't use pug/jade highlighting in a .vue file :disappointed: 

Is it fixed in the develop branch?

**Comment by psi-4ward** [comment]
perhaps we could "bountysource" ?

**Comment by mqhe2007** [comment]
同求，希望大大尽快支持pug语法，现在没有高亮和提示写着不太舒服。

**Comment by abou7mied** [comment]
webstorm started supporting VueJS officially, but currently it's available in EAP build
see their [blog post](https://blog.jetbrains.com/webstorm/2017/02/webstorm-2017-1-eap-171-2822/)
