### ISSUE TITLE
Reformat Code not working

### ISSUE THREAD

**Issue by ikristher** [henjue/vue-for-idea#42]
Seems like auto formatting line is not working on the latest version

**Comment by springeye** [comment]
Not automatically formatted. Manual formatting.
click "Code->Reformat Code"

**Comment by ikristher** [comment]
Yup that's what I did but didn't work, reverted to previous version and everything worked fine

**Comment by springeye** [comment]
I test everything to work properly.

**Comment by murbanowicz** [comment]
I confirm the same issue. Reformatting code is just giving some new lines and that's all. It was ok some time ago but now..

**Comment by springeye** [comment]
@mariaczi  I don't quite understand what you mean.Can I trouble you to see if the git image or video?My email henjue@gmail.com .Thank you very much.

**Comment by gtsigner** [comment]
Who has solved the problem，help me
