### ISSUE TITLE
*.vue 文件里template中的html代码显示有错误

### ISSUE THREAD

**Issue by hefengxian** [henjue/vue-for-idea#43]
WebStorm 今天更新之后变成这样了， 没更新的时候是好的插件版本：Version: 1.0.72
DOM确定编写格式良好，就是更新版本1.0.72之后，按提示重启IDE就不正常了，只有我一个人这样么？

![image](https://cloud.githubusercontent.com/assets/4338497/16142778/e2ec8972-349a-11e6-9892-04d036727e4c.png)

**Comment by springeye** [comment]
@hefengxian 可否把你template中的内容发给我测试下

**Comment by springeye** [comment]
Urgent fix this problem, 1.0.73 version, you can update the

**Comment by hefengxian** [comment]
Thanks a lot，但是我已经回退到5月版本了
