### ISSUE TITLE
"Plugin "vue-for-idea" was not loaded: required plugin "CoffeeScript" is disabled."

### ISSUE THREAD

**Issue by amcsi** [henjue/vue-for-idea#47]
I got this after updating to the latest version:

> Plugin Error
> Problems found loading plugins:
> Plugin "vue-for-idea" was not loaded: required plugin "CoffeeScript" is disabled.

This plugin shouldn't have to demand that I have CoffeeScript, should it?

**Comment by springeye** [comment]
@amcsi You need to install the coffeescript plug-in.Vue - for - idea relying on coffeescript plug-in
