### ISSUE TITLE
Vue support in other files (such as .html, .php)

### ISSUE THREAD

**Issue by spaceemotion** [henjue/vue-for-idea#5]
Hey, I was wanting to try out the the plugin, but it seems that its current scope is limited to `.vue` files. As I sometimes just need small snippets that I write directly into my laravel application's blade.php files, i was wondering if you could add support for vue (and its tags) to every html-like file type. Cheers!

**Comment by tristanbes** [comment]
or twig files for instance (`.html.twig`) ;)

**Comment by springeye** [comment]
@mrjeye do you think?

**Comment by krokofant** [comment]
This is why I installed this plugin but it seems it does not meet my requirements :(

I want to get rid of these errors in my .html files saying the vue attributes aren't valid.
<img width="282" alt="index_htm" src="https://cloud.githubusercontent.com/assets/5908498/14549001/3fe136de-02bc-11e6-8fdd-04893d3f2235.png">

**Comment by springeye** [comment]
Sorry, this plugin is mainly used for the.Vue template file. Other documents are not considered for the time being.
