### ISSUE TITLE
<template>标签不支持emmet写法

### ISSUE THREAD

**Issue by think2011** [henjue/vue-for-idea#50]
Hi，我使用的是webstorm，平时编写HTML都会用emmet语法来简写，例如输入`#app`然后按下`tab`键，会自动生成`<div id="app"></div>`。

但在vue文件里面对应的template标签却无法使用了，很困扰，请问能否解决呢？ ：）

**Comment by think2011** [comment]
目前使用的插件版本是 `Version: 1.0.73`

**Comment by zack24q** [comment]
尝试jade支持时发现的一个方法
打开[settings]=>[Editor]=>[Language Injections]，然后点右上角加号添加[XML Tag Injection]，然后Language的ID选成HTML，XML Tag的Local name填template，然后点OK保存，emmet可以用了

**Comment by springeye** [comment]
@think2011 
输入

``` html
div#app
```

再按tab键试试

**Comment by rauanmayemir** [comment]
@henjue Typing in '.row' won't work, you'll have to deliberately specify 'div.row'.

**Comment by think2011** [comment]
谢谢，最后的解决办法是在 setting -> file types 中把vue文件注册到html类型中，这样就能正常使用了。

好像这是webstorm最新的特性，可以通过设置 `type="text/ecmascript-6"` or `rel="stylesheet/scss"` 来设置配置标签内的语法高亮，似乎就用不上 vue-for-idea 插件了，而且.vue的icon也变成了html的icon。

**Comment by springeye** [comment]
其实是vue-for-idea 插件内处理了 type和rel...但是担心用户lang和type写的不对应就导致ide不提示错但编译提示错误，nighly通道去掉的type和rel的处理。
