### ISSUE TITLE
Sassy (SCSS) syntax is not recognized

### ISSUE THREAD

**Issue by iraklisg** [henjue/vue-for-idea#69]
Using <style lang="sass" rel="stylesheet/scss"> within a `.vue` module does not recognize the newer Sassy SCSS syntax. 
![image](https://cloud.githubusercontent.com/assets/3668360/19966347/0ade2c64-a1d4-11e6-824a-54259c9b42d1.png)

Using <style lang="scss" rel="stylesheet/scss"> recognize the SCSS syntax
![image](https://cloud.githubusercontent.com/assets/3668360/19966473/95a5fb92-a1d4-11e6-81d7-48d115500791.png)

However the module cannot be compiled if we use the lang="scss" (see [here](https://github.com/vuejs/laravel-elixir-vue-2/issues/15#issuecomment-258111113)  as well)

**Comment by psi-4ward** [comment]
Currently I use `vue.js` Plugin in PhpStorm and it works with `<style lang="scss" rel="stylesheet/scss">`

**Comment by iraklisg** [comment]
@psi-4ward  thank you for your reply, this is actually a different plugin (for anyone interested [here](https://github.com/postalservice14/vuejs-plugin) is the repo) which indeed works pretty well with `<style lang="scss" rel="stylesheet/scss">`

**Comment by psi-4ward** [comment]
Yes of course but also has no pug / jade template support.

This would be the killer feature for our team
