### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by menghuan758** [henjue/vue-for-idea#8]
### Some error occured when i installed the plugin for idea 14.

I'm using jdk 1.8

> Plugin 'io.j99.idea.vue' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.
> 
> java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
>     at io.j99.idea.vue.VueFileTypeFactory.createFileTypes(VueFileTypeFactory.kt)
>     at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.a(FileTypeManagerImpl.java:166)
>     at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initComponent(FileTypeManagerImpl.java:356)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter$1.getComponentInstance(ComponentManagerImpl.java:563)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:605)
>     at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:236)
>     at com.intellij.util.pico.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:223)
>     at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:210)
>     at org.picocontainer.alternatives.AbstractDelegatingMutablePicoContainer.getComponentInstance(AbstractDelegatingMutablePicoContainer.java:75)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponent(ComponentManagerImpl.java:124)
>     at com.intellij.openapi.application.impl.ApplicationImpl.createComponent(ApplicationImpl.java:357)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:115)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
>     at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:110)
>     at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:510)
>     at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:492)
>     at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:158)
>     at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:66)
>     at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
>     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
>     at java.awt.EventQueue.access$400(EventQueue.java:82)
>     at java.awt.EventQueue$2.run(EventQueue.java:676)
>     at java.awt.EventQueue$2.run(EventQueue.java:674)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
>     at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
>     at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
>     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
>     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
>     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
>     at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
> Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics PluginClassLoader[io.j99.idea.vue, 1.0.3]
>     at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
>     ... 33 more

**Comment by springeye** [comment]
@menghuan758 My test environment is idea 15, recommended to use idea 15

**Comment by menghuan758** [comment]
@henjue thanks.
